### ISSUE TITLE
Domain Randomization

### ISSUE THREAD

**Issue by potato23333** [eugenevinitsky/robust_RL_multi_adversary#53]
Sorry to bother you. Is your code containing domain randomization? If  it contains, how can I run it?
Thanks.

**Comment by eugenevinitsky** [comment]
Oh hi, I missed this! So all the domain randomization code is in https://github.com/eugenevinitsky/robust_RL_multi_adversary/blob/master/visualize/mujoco/transfer_tests.py and I think the logic in there is not too bad to follow?

**Comment by potato23333** [comment]
Thanks a lot
